# Generated by Django 2.0.4 on 2018-04-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hoca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ogrenci',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=13011907, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
