# Generated by Django 2.0.4 on 2018-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180503_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersdetaylari',
            name='ders_kodu',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
