# Generated by Django 2.0.4 on 2018-04-24 16:45

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dosyalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyalar',
            name='donem',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dosyalar',
            name='dosya_adi',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dosyalar',
            name='tablo',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dosyalar',
            name='yil',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dosyalar',
            name='dosya',
            field=models.FileField(upload_to='accounts/dosyalar', validators=[accounts.validators.validate_xls_file_extension]),
        ),
    ]
