# Generated by Django 2.0.4 on 2018-04-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180419_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad',
            field=models.CharField(default='00000000', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='soyad',
            field=models.CharField(default='00000000', max_length=32),
        ),
    ]
