# Generated by Django 2.0.4 on 2018-04-24 19:23

from django.db import migrations
#import xlrd
#import os

#dosyalarDirectory = os.path.join(os.path.dirname(__file__), "dosyalar")

#def populatedatabase(apps, schema_editor):
#    fakulteler_file = os.path.join(dosyalarDirectory, "fakulteler.xls")
#    fakulteModel = apps.get_model('accounts', 'fakulte')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180424_1645'),
    ]

    operations = [
    ]
