# Generated by Django 2.0.4 on 2018-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180503_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersdetaylari',
            name='ders_kodu',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
