# Generated by Django 2.0.4 on 2018-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180503_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='bolum',
            field=models.CharField(max_length=50),
        ),
    ]
