# Generated by Django 2.0.4 on 2018-04-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hoca',
            field=models.BooleanField(default=False, verbose_name='Hoca'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ogrenci',
            field=models.BooleanField(default=False, verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Yetkili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Kullanıcı adı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='yonetim',
            field=models.BooleanField(default=False, verbose_name='Yonetim Üyesi'),
        ),
    ]
