# Generated by Django 2.0.4 on 2018-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180503_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci_ders',
            name='ders_kodu',
            field=models.CharField(default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='ogrenci_ders',
            name='ogrenci_no',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
