# Generated by Django 2.0.4 on 2018-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180422_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogrenci',
            fields=[
                ('ogrenci_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('bolum_kodu', models.SmallIntegerField()),
                ('bolum', models.CharField(max_length=30)),
            ],
        ),
    ]
