# Generated by Django 2.0.4 on 2018-05-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180505_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='sorular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(default=None, max_length=512)),
            ],
        ),
    ]
