# Generated by Django 2.0.4 on 2018-04-22 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ogrenci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hoca',
            new_name='hoc',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ogrenci',
            new_name='ogr',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='yonetim',
            new_name='yon',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='accountID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
