# Generated by Django 2.0.5 on 2018-05-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sorular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anket',
            options={'verbose_name_plural': 'Anketler'},
        ),
        migrations.AlterModelOptions(
            name='bolum',
            options={'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AlterModelOptions(
            name='ders',
            options={'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='ders_anketi',
            options={'verbose_name_plural': 'Ders Anketleri'},
        ),
        migrations.AlterModelOptions(
            name='dersdetaylari',
            options={'verbose_name_plural': 'Ders Detayları'},
        ),
        migrations.AlterModelOptions(
            name='fakulte',
            options={'verbose_name_plural': 'Fakulteler'},
        ),
        migrations.AlterModelOptions(
            name='fakulte_bolum',
            options={'verbose_name_plural': 'Fakülte_Bölüm Tablosu'},
        ),
        migrations.AlterModelOptions(
            name='hoca',
            options={'verbose_name_plural': 'Hocalar'},
        ),
        migrations.AlterModelOptions(
            name='ogrenci',
            options={'verbose_name_plural': 'Öğrenciler'},
        ),
        migrations.AlterModelOptions(
            name='ogrenci_ders',
            options={'verbose_name_plural': 'Öğrenci_Ders Tablosu'},
        ),
        migrations.AlterModelOptions(
            name='sonuclar',
            options={'verbose_name_plural': 'Sonuçlar'},
        ),
        migrations.AlterModelOptions(
            name='sorular',
            options={'verbose_name_plural': 'Sorular'},
        ),
        migrations.AlterModelOptions(
            name='yonetim',
            options={'verbose_name_plural': 'Yönetim'},
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='donem',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='genelsonuc',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='katilim_orani',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc17',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc18',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc19',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc20',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc21',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc22',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc23',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc24',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc25',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc26',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc27',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc28',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc29',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc30',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='yil',
        ),
        migrations.AddField(
            model_name='sonuclar',
            name='ogrenci_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ogrenci'),
        ),
    ]
