# Generated by Django 2.0.4 on 2018-04-22 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180422_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoca',
            fields=[
                ('hoca_kodu', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('bolum_kodu', models.SmallIntegerField()),
                ('bolum', models.CharField(max_length=30)),
                ('accountID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
