# Generated by Django 2.0.5 on 2018-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180514_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuclar',
            name='ders_kodu',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='sonuclar',
            name='ogrenci_no',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
