# Generated by Django 2.0.4 on 2018-04-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hoca'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolum',
            fields=[
                ('bolum_kodu', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('bolum_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='hoca',
            name='bolum_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bolum'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='bolum_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bolum'),
        ),
    ]
