# Generated by Django 2.0.5 on 2018-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180514_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yonetim',
            name='id',
        ),
        migrations.AddField(
            model_name='yonetim',
            name='TCKimlik',
            field=models.CharField(default=0, max_length=11, primary_key=True, serialize=False),
        ),
    ]
