# Generated by Django 2.0.5 on 2018-05-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180517_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonetim',
            name='bolum_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bolum'),
        ),
        migrations.AlterField(
            model_name='yonetim',
            name='fakulte_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fakulte'),
        ),
    ]
