# Generated by Django 2.0.5 on 2018-05-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180517_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yonetim',
            name='TCKimlik',
        ),
        migrations.AddField(
            model_name='yonetim',
            name='YonetimID',
            field=models.CharField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
    ]
