# Generated by Django 2.0.5 on 2018-05-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180517_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc10',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc11',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc12',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc13',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc14',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc15',
        ),
        migrations.RemoveField(
            model_name='sonuclar',
            name='sonuc16',
        ),
    ]
